version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODE=dry_run
      - RUN_STRATEGY=false
      - DATABASE_URL=sqlite:///./trading_system.db
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./trades:/app/trades
      - ./cache:/app/cache
      - ./state.json:/app/state.json
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  # Optional: Add a database service if needed
  # database:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: trading_system
  #     POSTGRES_USER: trader
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: